# Ultralytics ğŸš€ AGPL-3.0 License - https://ultralytics.com/license

# Ultralytics YOLO11 object detection model with P3/8 - P5/32 outputs
# Model docs: https://docs.ultralytics.com/models/yolo11
# Task docs: https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024] # summary: 181 layers, 2624080 parameters, 2624064 gradients, 6.6 GFLOPs
  s: [0.50, 0.50, 1024] # summary: 181 layers, 9458752 parameters, 9458736 gradients, 21.7 GFLOPs
  m: [0.50, 1.00, 512] # summary: 231 layers, 20114688 parameters, 20114672 gradients, 68.5 GFLOPs
  l: [1.00, 1.00, 512] # summary: 357 layers, 25372160 parameters, 25372144 gradients, 87.6 GFLOPs
  x: [1.00, 1.50, 512] # summary: 357 layers, 56966176 parameters, 56966160 gradients, 196.0 GFLOPs

# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  # p1
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2 (320)
  
  # p2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4 (160)
  - [-1, 2, C3k2, [256, False, 0.25]] # 2 p2 (160) 
  
  # p3
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8 (80)
  - [-1, 2, C3k2, [512, False, 0.25]] # 4 p3 (80)
  
  # p4
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16 (40)
  - [-1, 2, C3k2, [512, True]] # 6 p4 (40)
  
  # p5
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32 (20)
  - [-1, 2, C3k2, [1024, True]] # 8 p5 (20)
  - [-1, 1, SPPF, [1024, 5]] # 9 p5 (20)
  - [-1, 2, C2PSA, [1024]] # 10 p5 (20)

# YOLO11n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 11 : P5 ì—…ìƒ˜í”Œë§ (20-> 40)
  - [[-1, 6], 1, Concat, [1]] # 12 : cat backbone P4 [p4+p5(up)] (40)
  - [-1, 2, C3k2, [512, False]] # 13 : head P4 (40)

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 14: 13 ì—…ìƒ˜í”Œë§ (40->80)
  - [[-1, 4], 1, Concat, [1]] # 15 : 14 cat backbone P3 [p3+(p4 + p5(up))(up)] (80)
  - [-1, 2, C3k2, [256, False]] # 16 : (P3/8-small) (80) -> detectì— ì‚¬ìš©

  - [-1, 1, Conv, [256, 3, 2]] # 17 : 16 conv(stride2) (80->40) ì¢€ ë” í° ë¬¼ì²´ ê°ì§€ ìœ„í•´
  - [[-1, 13], 1, Concat, [1]] # 18 : 17 cat head P4 (40)
  - [-1, 2, C3k2, [512, False]] # 19 : (P4/16-medium) (40) -> detectì— ì‚¬ìš©

  - [-1, 1, Conv, [512, 3, 2]] # 20 : 19 conv(stride2) (40 -> 20) ì¢€ ë”ë” í° ë¬¼ì²´ ê°ì§€ ìœ„í•´
  - [[-1, 10], 1, Concat, [1]] # 21 : 19 cat head P5 (20)
  - [-1, 2, C3k2, [1024, True]] # 22 : (P5/32-large) -> detectì— ì‚¬ìš© (20)

  - [[16, 19, 22], 1, Detect, [nc]] # 23 : Detect(P3, P4, P5)
